
#ifndef __CONFIGS_COMM_H__
#define __CONFIGS_COMM_H__

#include "board.h"

#ifndef CONFIG_WDT_CHIPSET
#define CONFIG_WDT_CHIPSET ""
#endif

#ifndef CONFIG_HWM_VOLTAGE_0_ENABLE
#define CONFIG_HWM_VOLTAGE_0_ENABLE 0
#endif

#ifndef CONFIG_HWM_VOLTAGE_1_ENABLE
#define CONFIG_HWM_VOLTAGE_1_ENABLE 0
#endif

#ifndef CONFIG_HWM_VOLTAGE_2_ENABLE
#define CONFIG_HWM_VOLTAGE_2_ENABLE 0
#endif

#ifndef CONFIG_HWM_VOLTAGE_3_ENABLE
#define CONFIG_HWM_VOLTAGE_3_ENABLE 0
#endif

#ifndef CONFIG_HWM_VOLTAGE_4_ENABLE
#define CONFIG_HWM_VOLTAGE_4_ENABLE 0
#endif

#ifndef CONFIG_HWM_VOLTAGE_5_ENABLE
#define CONFIG_HWM_VOLTAGE_5_ENABLE 0
#endif

#ifndef CONFIG_HWM_VOLTAGE_6_ENABLE
#define CONFIG_HWM_VOLTAGE_6_ENABLE 0
#endif

#ifndef CONFIG_HWM_VOLTAGE_7_ENABLE
#define CONFIG_HWM_VOLTAGE_7_ENABLE 0
#endif

#ifndef CONFIG_HWM_TEMPERATURE_0_ENABLE
#define CONFIG_HWM_TEMPERATURE_0_ENABLE 0
#endif

#ifndef CONFIG_HWM_TEMPERATURE_1_ENABLE
#define CONFIG_HWM_TEMPERATURE_1_ENABLE 0
#endif

#ifndef CONFIG_HWM_TEMPERATURE_2_ENABLE
#define CONFIG_HWM_TEMPERATURE_2_ENABLE 0
#endif

#ifndef CONFIG_HWM_FAN_0_ENABLE
#define CONFIG_HWM_FAN_0_ENABLE 0
#endif

#ifndef CONFIG_HWM_FAN_1_ENABLE
#define CONFIG_HWM_FAN_1_ENABLE 0
#endif

#ifndef CONFIG_HWM_FAN_2_ENABLE
#define CONFIG_HWM_FAN_2_ENABLE 0
#endif

#ifndef CONFIG_HWM_PWM_0_ENABLE
#define CONFIG_HWM_PWM_0_ENABLE 0
#endif

#ifndef CONFIG_HWM_PWM_1_ENABLE
#define CONFIG_HWM_PWM_1_ENABLE 0
#endif

#ifndef CONFIG_HWM_PWM_2_ENABLE
#define CONFIG_HWM_PWM_2_ENABLE 0
#endif

#ifndef CONFIG_HWM_PWM_3_ENABLE
#define CONFIG_HWM_PWM_3_ENABLE 0
#endif

#ifndef CONFIG_HWM_PWM_4_ENABLE
#define CONFIG_HWM_PWM_4_ENABLE 0
#endif

#ifndef CONFIG_HWM_PWM_5_ENABLE
#define CONFIG_HWM_PWM_5_ENABLE 0
#endif

#ifndef CONFIG_HWM_PWM_6_ENABLE
#define CONFIG_HWM_PWM_6_ENABLE 0
#endif

#ifndef CONFIG_MISC_0_ENABLE
#define CONFIG_MISC_0_ENABLE 0
#endif

#ifndef CONFIG_MISC_1_ENABLE
#define CONFIG_MISC_1_ENABLE 0
#endif

#ifndef CONFIG_MISC_2_ENABLE
#define CONFIG_MISC_2_ENABLE 0
#endif

#ifndef CONFIG_MISC_3_ENABLE
#define CONFIG_MISC_3_ENABLE 0
#endif

#ifndef CONFIG_MISC_4_ENABLE
#define CONFIG_MISC_4_ENABLE 0
#endif

#ifndef CONFIG_MISC_5_ENABLE
#define CONFIG_MISC_5_ENABLE 0
#endif

#ifndef CONFIG_MISC_6_ENABLE
#define CONFIG_MISC_6_ENABLE 0
#endif

#ifndef CONFIG_MISC_7_ENABLE
#define CONFIG_MISC_7_ENABLE 0
#endif

#ifndef CONFIG_MISC_8_ENABLE
#define CONFIG_MISC_8_ENABLE 0
#endif

#ifndef CONFIG_MISC_9_ENABLE
#define CONFIG_MISC_9_ENABLE 0
#endif

#endif /** __CONFIGS_COMM_H__ */